name: Build Test and push
on: [push]
env:
  BACKEND_IMAGE_NAME: student_details_service
  REPO_NAME: ikoko3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Student Service docker
      run: |
        docker build student_service -t $REPO_NAME/$BACKEND_IMAGE_NAME
    - name: run Student Service docker
      run: |
        docker run -d -p 3000:3000 $REPO_NAME/$BACKEND_IMAGE_NAME:latest && \
          docker ps && sleep 5


    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push backend image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$BACKEND_IMAGE_NAME

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload ZIP to S3
      run: |
        aws s3 cp student_service-${{ github.run_number }}.zip s3://elasticbeanstalk-eu-central-1-677276075513/


    - name: Generate Deployment Package
      run: zip -r student_service.zip student_service -x "student_service/.git/*"

    - name: Upload to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name "StudentService" \
          --version-label "v-${{ github.run_number }}" \
          --source-bundle S3Bucket="elasticbeanstalk-eu-central-1-677276075513",S3Key="student_service-${{ github.run_number }}.zip"

        aws elasticbeanstalk update-environment \
          --environment-name "StudentService-env" \
          --version-label "v-${{ github.run_number }}"