name: Build Test and push
on: [push]
env:
  BACKEND_IMAGE_NAME: student_details_service
  FRONTEND_IMAGE_NAME: student_interface
  REPO_NAME: ikoko3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Student Service docker
      run: |
        docker build student_service -t $REPO_NAME/$BACKEND_IMAGE_NAME
    - name: run Student Service docker
      run: |
        docker run -d -p 3000:3000 $REPO_NAME/$BACKEND_IMAGE_NAME:latest && \
          docker ps && sleep 5

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$BACKEND_IMAGE_NAME