name: Build Test and push
on: [push]
env:
  BACKEND_IMAGE_NAME: student_details_service
  FRONTEND_IMAGE_NAME: student_interface
  REPO_NAME: ikoko3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build . -t $REPO_NAME/$BACKEND_IMAGE_NAME
    - name: run docker
      run: |
        docker run -d -p 3000:3000 $REPO_NAME/$BACKEND_IMAGE_NAME:latest && \
          docker ps && sleep 5

    - name: "Check files existence"
      uses: andstor/file-existence-action@v2
      with:
        files: "postman/collection.json,postman/environment.json"
        fail: true

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$BACKEND_IMAGE_NAME