name: Build Test and push
on: [push]
env:
  BACKEND_IMAGE_NAME: student_details_service
  REPO_NAME: ikoko3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Student Service docker
      run: |
        docker build student_service -t $REPO_NAME/$BACKEND_IMAGE_NAME
    - name: run Student Service docker
      run: |
        docker run -d -p 3000:3000 $REPO_NAME/$BACKEND_IMAGE_NAME:latest && \
          docker ps && sleep 5


    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push backend image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$BACKEND_IMAGE_NAME

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Elastic Beanstalk CLI
      run: |
        pip install awsebcli --upgrade

    - name: Initialize Elastic Beanstalk (If Not Already Initialized)
      run: |
        eb init ${{ secrets.EB_APPLICATION_NAME }} --platform docker --region ${{ secrets.AWS_REGION }}

    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy ${{ secrets.EB_ENVIRONMENT_NAME }}
